import './globals.css'
import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Postgress CRUD with NextJS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Navbar />
        <main> {children} </main>

      </body>
    </html>
  )
}